#!/bin/bash

echo "▶ Running pre-commit hook..."
echo "▶ Running dart formatting check..."

if ! output=$(dart format . --set-exit-if-changed); then
    echo "$output"
    echo "⚠ Found formatting issue. Please review and commit again!"
    exit 1
fi

echo "✅ Pre-commit checks passed!"
exit 0